// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WenKaiTsai.HotelManagementSystem.Infrastructure.Data;

namespace WenKaiTsai.HotelManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HotelManagementSystemDbContext))]
    [Migration("20210727002032_CreateRoomCustomerRelationship")]
    partial class CreateRoomCustomerRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WenKaiTsai.HotelManagementSystem.ApplicationCore.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDRESS")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ADVANCE")
                        .HasColumnType("money");

                    b.Property<int?>("BOOKINGDAYS")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CHECKIN")
                        .HasColumnType("datetime2");

                    b.Property<string>("CNAME")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("ROOMNO")
                        .HasColumnType("int");

                    b.Property<int?>("TOTALPERSONS")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ROOMNO");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("WenKaiTsai.HotelManagementSystem.ApplicationCore.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RTCODE")
                        .HasColumnType("int");

                    b.Property<bool?>("STATUS")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("WenKaiTsai.HotelManagementSystem.ApplicationCore.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("RENT")
                        .HasColumnType("money");

                    b.Property<string>("RTDESC")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("WenKaiTsai.HotelManagementSystem.ApplicationCore.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("money");

                    b.Property<int?>("ROOMNO")
                        .HasColumnType("int");

                    b.Property<string>("SDESC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SERVICEDATE")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("WenKaiTsai.HotelManagementSystem.ApplicationCore.Entities.Customer", b =>
                {
                    b.HasOne("WenKaiTsai.HotelManagementSystem.ApplicationCore.Entities.Room", "Room")
                        .WithMany("Customers")
                        .HasForeignKey("ROOMNO");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WenKaiTsai.HotelManagementSystem.ApplicationCore.Entities.Room", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
